### ISSUE TITLE
Typos in README instructions

### ISSUE THREAD

**Issue by finnbear** [alon2712/CEO-Express#2]
Hello,

I noticed a few typos in your instructions:

1. `cd backend` instead of `cd BackEnd`
```bash
finnb@localhost:~/CEO-Express$ cd backend
bash: cd: backend: No such file or directory
```
This typo is repeated [here](https://github.com/alon2712/CEO-Express/blob/f9b0b33b84b1bf99d5e4b43898f36136ef1f7e99/front-end/package.json#L29) too.

2. `npm install && cd front-end` instead of `cd front-end && npm install`
```bash
finnb@localhost:~/CEO-Express$ npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/finnb/CEO-Express/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/finnb/CEO-Express/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/finnb/.npm/_logs/2024-02-18T02_03_16_347Z-debug-0.log
```

Thanks!

## Context

I followed the instructions, as part of peer review, on a brand new Ubuntu 22.04 VM.

**Comment by juliakharchenko** [comment]
Hello! We have just modified the README so it reflects these changes, thanks for the feedback!

**Comment by finnbear** [comment]
Sure! You may also want to fix the first typo in `package.json` too (https://github.com/alon2712/CEO-Express/blob/35b41ece90d00f955434c3c256edf60f5b815a8e/front-end/package.json#L29)

**Comment by juliakharchenko** [comment]
Good catch! Just changed it:)
