### ISSUE TITLE
Unable to run frontend (node 12)

### ISSUE THREAD

**Issue by finnbear** [alon2712/CEO-Express#3]
Hello,

I was unable to run your frontend:
```bash
finnb@localhost:~/CEO-Express/front-end$ npm run start

> front-end@0.1.0 start
> react-scripts start

Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.
 ```

Thanks for investigating this!

## Context

I followed the instructions, as part of peer review, on a brand new Ubuntu 22.04 VM. I ended up with the following software and package versions:

```bash
finnb@localhost:~/CEO-Express/front-end$ npm version
{
  'front-end': '0.1.0',
  npm: '8.5.1',
  node: '12.22.9',
  v8: '7.8.279.23-node.56',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.6',
  http_parser: '2.9.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2023c',
  unicode: '14.0'
}
```

If you need a different version of Node.js, please specify it in the instructions! We're happy to test again once resolved.

**Comment by Zohar-Le** [comment]
I was able to run frontend on my mac. I got a proxy request error that I'm not sure how to address. Here you can take a look. 
<img width="730" alt="image" src="https://github.com/alon2712/CEO-Express/assets/109646359/0bf2dc4e-f110-417e-9e71-c93470176e90">
I'm assuming that I probably did not run backend correctly.
<img width="480" alt="image" src="https://github.com/alon2712/CEO-Express/assets/109646359/7140ecbc-48d2-47f1-8fd5-aa1e129874dc">

**Comment by brooklynxzhu** [comment]
Was able to run frontend on localhost:3030, getting a 403 forbidden error though, no error message in the terminal
<img width="1121" alt="Screenshot 2024-02-20 at 10 50 20 PM" src="https://github.com/alon2712/CEO-Express/assets/155672757/d1190156-bd9a-4cad-9305-a3be1490faf3">

here is my npm version:
<img width="335" alt="Screenshot 2024-02-20 at 11 02 53 PM" src="https://github.com/alon2712/CEO-Express/assets/155672757/c0026717-c317-492a-aecb-a59e8c3aa2ad">

**Comment by juliakharchenko** [comment]
We have fixed the README to reflect these changes; thank you for the input!

**Comment by finnbear** [comment]
I think it would be useful to specify a minimum Node JS version, since it seemed like node 12 was too low :thinking:

**Comment by juliakharchenko** [comment]
Thanks for pointing it out! I just added it to the README:)
