### ISSUE TITLE
Developer guidelines not found

### ISSUE THREAD

**Issue by finnbear** [alon2712/CEO-Express#4]
Hello,

Please add self-contained, well-structured developer guidelines e.g. `CONTRIBUTING.md` or Wiki pages, if you haven't already, and link to them in a conspicuous place in the README.

They should mention how to add new tests.

## Context

This feedback is part of peer review. We're happy to review your developer guide once you add it.

**Comment by juliakharchenko** [comment]
We have just linked the developer guidelines into the README, thank you for the comment!

**Comment by finnbear** [comment]
Your instruction improvements are nice but I didn't see a mention of how to create issues, pull requests, tests, etc.

**Comment by juliakharchenko** [comment]
We are working on it right now and will notify you once we complete it.

**Comment by juliakharchenko** [comment]
We have just updated our developer guidelines in our README! Please let us know if this is sufficient :-)

**Comment by finnbear** [comment]
It's certainly better now!
