### ISSUE TITLE
instructions.txt and BackEnd/TEST_README seemingly redundant with README instructions, unable to run backend

### ISSUE THREAD

**Issue by finnbear** [alon2712/CEO-Express#5]
Hello,

I noticed your other instructions, `instructions.txt`, is largely redundant with your README. I suggest having one definitive instruction guide.

When I try `instructions.txt`, I get:
```bash
finnb@localhost:~/CEO-Express/front-end$ npm run start-backend

> front-end@0.1.0 start-backend
> cd ../backend && env/bin/flask run --no-debugger

sh: 1: cd: can't cd to ../backend
```
Correcting `package.json` to `cd BackEnd` instead of `cd backend`, I get:
```bash
finnb@localhost:~/CEO-Express/front-end$ npm run start-backend

> front-end@0.1.0 start-backend
> cd ../BackEnd && env/bin/flask run --no-debugger
sh: 1: env/bin/flask: not found
```
And then, following `instructions.txt` again, I get:
```bash
finnb@localhost:~/CEO-Express/BackEnd$ source env/bin/activate
bash: env/bin/activate: No such file or directory
```

## Context

I followed the instructions, as part of peer review, on a brand new Ubuntu 22.04 VM. We're happy to test again when resolved.

**Comment by brooklynxzhu** [comment]
Using Mac:
Unable to go past step 2 in the instructions.txt, returns with  `sh: env/bin/flask: No such file or directory`
<img width="693" alt="Screenshot 2024-02-20 at 11 11 13 PM" src="https://github.com/alon2712/CEO-Express/assets/155672757/e0bf8a53-a4f9-48b6-9c66-2e3ea3eb60e4">

```
(base) brooklynzhu@Brooklyns-MacBook-Pro-2 BackEnd % source env/bin/activate
source: no such file or directory: env/bin/activate
```

**Comment by juliakharchenko** [comment]
Thanks for the feedback! We fixed it via this commit: https://github.com/alon2712/CEO-Express/commit/a5276f38850923d7c226717b0b623a7a59b1e0e9
