### ISSUE TITLE
CI setup could be improved

### ISSUE THREAD

**Issue by finnbear** [alon2712/CEO-Express#6]
Hello,

I noticed your [CI setup](https://github.com/alon2712/CEO-Express/blob/main/.github/workflows/python-publish.yml) lacks the typical steps of building, testing, format checking, and linting for the backend, and is completely missing for the frontend.

An improved CI setup (starting by running the tests you already created) could help detect issues with each commit, increasing confidence in each merge.

## Context

This feedback is for peer review. We're happy to review again once resolved.

**Comment by finnbear** [comment]
It looks like you previously had a better CI setup but it was deleted by this commit: https://github.com/alon2712/CEO-Express/commit/c04b20584226849cf1c76982d9582d849091ada6

Assuming this was a mistake, note that using pull requests instead of committing directly to `main` might reduce the chance of mistakes in the future.

**Comment by juliakharchenko** [comment]
We now have a couple of different workflows, and have reverted our previous yaml that we had to one of our workflows! Thank you for taking the time to point this out, we appreciate it!
