### ISSUE TITLE
Hardcoded API key

### ISSUE THREAD

**Issue by finnbear** [alon2712/CEO-Express#7]
Hello,

I noticed you hardcoded a secret API key [here](https://github.com/alon2712/CEO-Express/blob/f9b0b33b84b1bf99d5e4b43898f36136ef1f7e99/BackEnd/base.py#L26). You should consider it compromised and rotate the key. In the future, we suggest using some other mechanism like environment variables, `.gitignore`'d files, or a secret management service.

## Context

This feedback is part of peer review.

**Comment by juliakharchenko** [comment]
Hello, thank you for your feedback! In future productions, we are going to commit our API key variable in the form of an empty string so that each user will be able to user their own private API key to access our service.

**Comment by finnbear** [comment]
Thank you! I can confirm this is fixed in https://github.com/alon2712/CEO-Express/commit/36ba43bc258a1b954fe3ba0b539efae491c91acb :ok_hand:
